### ISSUE TITLE
Error processing checkout.

### ISSUE THREAD

**Issue by derrickhorton** [anypay/anypay-woocommerce#4]
When user checks out, error message reads,

"Error processing checkout. Please try again."

This occurs when the user is supposed to reach the payment screen.

I suspect this may have something to do with the API endpoint URL that is called.

**Comment by derrickhorton** [comment]
The API call may need to be reworked.

This is an error that appeared yesterday:

```
% curl -d '{"amount":1,"redirect_url":"https:\/\/derrickjhorton.com\/checkout\/order-received\/26\/?key=wc_order_SM9xOsLTnVsuf","webhook_url":"https:\/\/derrickjhorton.com\/?wc-api=wc_gateway_anypay","external_id":26,"wordpress_site_url":"https:\/\/derrickjhorton.com"}' -H 'Content-type: application/json' -H 'Authorization: Basic YTpi' https://api.anypayx.com/accounts/21013/invoices

{"statusCode":500,"error":"plugin.createInvoice is not a function","message":"plugin.createInvoice is not a function"}
```

According to @owenkellogg , `plugin.createinvoice` has been out of operation for a long time.

**Comment by derrickhorton** [comment]
<img width="668" alt="Screenshot 2023-05-18 at 01 46 21" src="https://github.com/anypay/anypay-woocommerce/assets/4019818/a971afcb-b4a1-4ad9-ba03-8cef6311df63">

**Comment by pshenmic** [comment]
https://github.com/anypay/anypay-woocommerce/pull/10
